# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170919_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'ordering': ['rank'], 'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
    ]
