# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_auto_20170919_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='billboard_current_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranks',
            name='most_related_youtube_vid_id',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ranks',
            name='rank',
            field=models.FloatField(default=0.0),
        ),
    ]
